version: "2.2"
services:
  api:
    build: 
      context: ./
      dockerfile: Dockerfile
    environment: 
      PORT: "7001"
    ports:
      - "7001:7001"
  front:
    build: 
        context: ../buy-sell-now
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment: 
      REACT_APP_API: "http://localhost:7001/"
