on:
  push:
    branches: ["main", "dev"]
jobs:  
  run-server:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: apk add --update nodejs npm
    - run: npm install
    - run: node app.js
