name: deploy server

on:
  push:
    branches: ["main", "dev"]
jobs:  
  run-server:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: pm2 restart buysellnowapi
